#!/usr/bin/with-contenv bash

# create our folders
mkdir -p \
	/config/{conf,data,logs}


# create symlinks for config
symlinks=( \
/usr/lib/unifi-video/conf \
/usr/lib/unifi-video/data \
/usr/lib/unifi-video/logs )

for i in "${symlinks[@]}"
do
[[ -L "$i" && ! "$i" -ef /config/"$(basename "$i")"  ]] && unlink "$i"
[[ ! -L "$i" ]] && ln -s /config/"$(basename "$i")" "$i"
done

# permissions
chown -R abc:abc \
	/config \
	/usr/lib/unifi